---
title: "An analysis of sinoracial prejudice in Western media"
author: "Johnny Breen"
date: "26/08/2019"
output: github_document
---

## Package requirements

```{r}
required_packages <- c("tidyverse", "tidytext")

for (pkg in required_packages) {
  if (!pkg %in% installed.packages()) {
    install.packages(pkg, dependencies = TRUE)
  }
  library(pkg, character.only = TRUE)
}
```


## Read in data

```{r}
data_path <- "/Users/Johnny/Desktop/Data Science/R/Project NY Times/Extractor script/article-extractions"

data_names <- list.files(data_path) %>% 
  keep(~ str_detect(., regex("uk|states|china|japan", ignore_case = TRUE)))

data_raw <- map(data_names, ~ mutate(read_csv(file = paste(data_path, ., sep = "/")), file_name = .))

data_merged <- data_raw %>%
  reduce(rbind) %>%
  mutate(file_name = str_extract(file_name, "(uk|states|china|japan)"))
```

## Analyse data

```{r}
data_unnested <- data_merged %>%
  unnest_tokens(output = "word", input = "article_description") %>%
  anti_join(stop_words) %>%
  filter(str_detect(word, "[a-z]"))

nrc_sentiments <- data_unnested %>%
  left_join(get_sentiments("nrc")) 

bing_sentiments <- data_unnested %>%
  left_join(get_sentiments("bing")) 

afinn_sentiments <- data_unnested %>%
  left_join(get_sentiments("afinn")) 
```

## Visualise the sentiments

```{r}
afinn_sentiments %>%
  group_by(article_id, file_name) %>%
  summarise(total_score = sum(score, na.rm = TRUE)) %>%
  ungroup() %>%
  ggplot(aes(x = total_score, colour = file_name)) +
  geom_density() +
  facet_wrap(~file_name)

nrc_sentiments %>%
  filter(!is.na(sentiment)) %>%
  count(sentiment, file_name) %>%
  group_by(file_name) %>%
  mutate(sentiment = fct_reorder(sentiment, n)) %>%
  ungroup() %>%
  ggplot(aes(x = sentiment, y = n)) +
  geom_col() +
  coord_flip() +
  facet_wrap(~file_name)
```

## TF-IDF analysis

```{r}
data_tf_idf <- data_unnested %>%
  count(file_name, word) %>%
  bind_tf_idf(term = "word", document = "file_name", n = n)

data_tf_idf %>%
  group_by(file_name) %>%
  top_n(n = 20, wt = tf_idf) %>%
  mutate(word = fct_reorder(word, tf_idf)) %>%
  ungroup() %>%
  ggplot(aes(x = word, y = tf_idf)) +
  geom_col() +
  coord_flip() + 
  facet_wrap(~file_name, scales = "free")
```

